export const TextConstants = {
  LocationName: "Location name",
  Address: "Address",
  LocationPhoneNumber: "Location phone",
  LocationContact: "Location contact",
  LocalStreetPlaceHolder: '1234 Sesame Street, Sacramento CA 95691',
  HowDoesLocation: "How does this location fulfill orders?",
  StreetAddress: "Street address",
  AddNewLocation: "Add new location",
  Country: "Country",
  SaveChanges: "Save changes",
  Cancel: "Cancel",
  Back: "Back",
  ChangePassword: "Change password",
  setPasswordText: "Set a permanent password to Sign in to your account",
  Password: "Password",
  AccountSecurity: "Account security",
  ChooseLocation: "Choose location",
  AddLocation:'Add location',
  EditLocation: 'Edit location',
  LoginAccount: "Sign in to your account",
  WelcomeText: "Welcome back! Please enter your credentials to access your Pickup Pointe account.",
  PICKUPPOINTE: "PICKUP POINTE",
  EmailAddress: "Email address",
  SignIn: "Sign in",
  SignInClover: 'Sign in with Clover',
  Integrations: 'Integrations'
};
