export const products = [
  {
    shopId: '6708e70e4a8281ebea35e71d',
    id: 'shop1',
    title: "Fugazzi's",
    subtitle: 'California cuisine',
    category: 'Mom & Pops Eateries',
    logo: 'logo_1',
    remain: 3,
    product_img: "product_1.jpg",
    price_from: '4.00',
    price_to: '4.50',
    unit: 'loaf',
    rating: 4.8,
    delivery: 'Pickup & delivery',
    delivery_type: '1',
    delivery_fee: '3.99',
    distance: '1.2',
    location: 'anywhere',
    background: 'rgba(60, 23, 5, 0.04)',
    savings_late: 20,
  },
  {
    shopId: '6708e7d84a8281ebea35e733',
    id: 'shop2',
    title: "Los Arbolitos Mexican Food & Burgers",
    subtitle: 'Mexican, Ceviche, Seafood',
    category: 'Mom & Pops Eateries',
    logo: 'logo_2',
    remain: 4,
    product_img: "product_2.png",
    price_from: '3.00',
    price_to: '3.50',
    unit: 'loaf',
    rating: 4.8,
    delivery: 'Pickup & delivery',
    delivery_type: '1',
    delivery_fee: '3.99',
    distance: '3.4',
    location: 'local',
    savings_late: 30,
  },
  {
    shopId: '6708e8334a8281ebea35e754',
    id: 'shop3',
    title: "Aloha Express",
    subtitle: 'Hawaiian, Seafood, Bowls',
    category: 'Mom & Pops Eateries',
    logo: 'logo_3',
    remain: 1,
    product_img: "product_3.png",
    price_from: '10.00',
    price_to: '12.00',
    unit: 'jar',
    rating: '5.0',
    delivery: 'Pickup & delivery',
    delivery_type: '2',
    delivery_fee: '3.99',
    distance: '2.7',
    location: 'local',
    savings_late: 22,
  },
  {
    shopId: '6708e8d84a8281ebea35e767',
    id: 'shop4',
    title: "Cafe India",
    subtitle: 'Indian, Soups, Coffee',
    category: 'Mom & Pops Eateries',
    logo: 'logo_4',
    remain: 1,
    product_img: "food_2",
    price_from: '10.00',
    price_to: '12.00',
    unit: 'jar',
    rating: '5.0',
    delivery: 'Pickup & delivery',
    delivery_type: '2',
    delivery_fee: '3.99',
    distance: '2.7',
    location: 'local',
    savings_late: 18,
  },
  {
    shopId: '6708e9234a8281ebea35e77f',
    id: 'shop5',
    title: "Javis Taco Shack",
    subtitle: 'Mexican, Salads, Alcohol',
    category: 'Mom & Pops Eateries',
    logo: 'logo_5',
    remain: 1,
    product_img: "food_3",
    price_from: '10.00',
    price_to: '12.00',
    unit: 'jar',
    rating: '5.0',
    delivery: 'Pickup & delivery',
    delivery_type: '2',
    delivery_fee: '3.99',
    distance: '2.7',
    location: 'local',
    savings_late: 33,
  },
  {
    shopId: '6708e9794a8281ebea35e78d',
    id: 'shop6',
    title: "Boston Pizza",
    subtitle: 'Pizza, Italian, Salads, Alcohol',
    category: 'Mom & Pops Eateries',
    logo: 'logo_6',
    remain: 1,
    product_img: "food_4",
    price_from: '10.00',
    price_to: '12.00',
    unit: 'jar',
    rating: '5.0',
    delivery: 'Pickup & delivery',
    delivery_type: '2',
    delivery_fee: '3.99',
    distance: '2.7',
    location: 'local',
    savings_late: 20,
  },
  {
    shopId: '6708e9b54a8281ebea35e79b',
    id: 'shop7',
    title: "Pokerito",
    subtitle: 'Asian, Healthy, Wraps',
    category: 'Mom & Pops Eateries',
    logo: 'logo_7',
    remain: 1,
    product_img: "food_5",
    price_from: '10.00',
    price_to: '12.00',
    unit: 'jar',
    rating: '5.0',
    delivery: 'Pickup & delivery',
    delivery_type: '2',
    delivery_fee: '3.99',
    distance: '2.7',
    location: 'local',
    savings_late: 12,
  },
  {
    shopId: '6708e9e74a8281ebea35e7a9',
    id: 'shop8',
    title: "Simply Mediterranean",
    subtitle: 'Mediterranean, Wraps, Salads',
    category: 'Mom & Pops Eateries',
    logo: 'logo_8',
    remain: 1,
    product_img: "food_6",
    price_from: '10.00',
    price_to: '12.00',
    unit: 'jar',
    rating: '5.0',
    delivery: 'Pickup & delivery',
    delivery_type: '2',
    delivery_fee: '3.99',
    distance: '2.7',
    location: 'local',
    savings_late: 23,
  },
];
